from django.conf import settings

# Test validator
TEST_STRUCTURE_VALIDATOR_FILE_ALLOWLIST = []
TEST_STRUCTURE_VALIDATOR_FILE_WHITELIST = TEST_STRUCTURE_VALIDATOR_FILE_ALLOWLIST
try:
    TEST_STRUCTURE_VALIDATOR_BASE_DIR = settings.BASE_DIR
except AttributeError:
    TEST_STRUCTURE_VALIDATOR_BASE_DIR = ""
TEST_STRUCTURE_VALIDATOR_BASE_APP_NAME = "apps"
TEST_STRUCTURE_VALIDATOR_APP_LIST = settings.INSTALLED_APPS
TEST_STRUCTURE_VALIDATOR_IGNORED_DIRECTORY_LIST = []
TEST_STRUCTURE_VALIDATOR_MISPLACED_TEST_FILE_ALLOWLIST = []
TEST_STRUCTURE_VALIDATOR_MISPLACED_TEST_FILE_WHITELIST = TEST_STRUCTURE_VALIDATOR_MISPLACED_TEST_FILE_ALLOWLIST
