# Generated by Django 5.0.7 on 2024-07-15 08:45

import ambient_toolbox.mixins.bleacher
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BleacherMixinModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
            ],
            bases=(ambient_toolbox.mixins.bleacher.BleacherMixin, models.Model),
        ),
    ]
