# Generated by Django 3.2.20 on 2023-10-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypermissionmodelmixin',
            options={'default_permissions': [], 'managed': False},
        ),
    ]
