# Generated by Django 6.1 on 2026-08-27 11:23

import ambient_toolbox.mixins.validation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_modelwithm2mtouser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelWithValidateConstraintsMixin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value__lte", 10)),
                        name="testapp_model_with_validate_constraints_mixin_value_lte_10",
                        violation_error_message="Value must not exceed 10.",
                    )
                ],
            },
            bases=(ambient_toolbox.mixins.validation.ValidateConstraintsOnSaveMixin, models.Model),
        ),
    ]
